"""
Audit Agent — Verifies fixes and generates post-mortem reports.
Re-queries metrics after remediation to confirm resolution.
"""

import asyncio
import json
from datetime import datetime, timezone
from pathlib import Path

import structlog

from tools.metrics_reader import MetricsReader
from config.settings import Settings

logger = structlog.get_logger()


class AuditAgent:
    def __init__(self, metrics_reader: MetricsReader, settings: Settings):
        self.metrics = metrics_reader
        self.settings = settings

    async def verify_after_delay(self, delay_seconds: int, service: str, action_taken: str):
        """Wait, then verify the fix worked. Called as a background task."""
        logger.info(
            "audit_scheduled",
            delay=delay_seconds,
            service=service,
            action=action_taken,
        )
        await asyncio.sleep(delay_seconds)

        # Re-check common health metrics
        checks = {
            "cpu": f'node_cpu_usage_percent{{service="{service}"}}',
            "memory": f'node_memory_usage_percent{{service="{service}"}}',
            "disk": f'node_disk_usage_percent{{service="{service}"}}',
        }

        results = {}
        all_ok = True

        for name, promql in checks.items():
            try:
                value = await self.metrics.query_value(promql)
                threshold = {"cpu": 90, "memory": 95, "disk": 90}.get(name, 90)
                ok = value < threshold
                results[name] = {"value": value, "threshold": threshold, "ok": ok}
                if not ok:
                    all_ok = False
            except Exception as e:
                results[name] = {"error": str(e), "ok": False}
                all_ok = False

        # Generate post-mortem
        report = self._generate_postmortem(
            service=service,
            action_taken=action_taken,
            results=results,
            resolved=all_ok,
        )

        logger.info(
            "audit_complete",
            service=service,
            resolved=all_ok,
            results=results,
        )

        return {"resolved": all_ok, "results": results, "report": report}

    async def check(self, metric: str, threshold: float, service: str, action_taken: str) -> dict:
        """Manual audit check for a specific metric."""
        try:
            promql = f'{metric}{{service="{service}"}}'
            value = await self.metrics.query_value(promql)
            ok = value < threshold

            result = {
                "metric": metric,
                "value": value,
                "threshold": threshold,
                "resolved": ok,
                "service": service,
                "action_taken": action_taken,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }

            if not ok:
                result["recommendation"] = (
                    f"Metric {metric} still at {value:.1f} (threshold: {threshold}). "
                    "Consider Level 2 intervention: rollback to last stable image."
                )

            return result

        except Exception as e:
            return {
                "metric": metric,
                "error": str(e),
                "resolved": False,
                "recommendation": "Unable to verify — check VictoriaMetrics connectivity.",
            }

    def _generate_postmortem(
        self, service: str, action_taken: str, results: dict, resolved: bool
    ) -> str:
        """Generate a Markdown post-mortem report."""
        now = datetime.now(timezone.utc)
        status = "RESOLVED" if resolved else "UNRESOLVED — ESCALATION NEEDED"

        report = f"""# Post-Mortem Report

## Incident Summary
- **Service:** {service}
- **Action Taken:** {action_taken}
- **Status:** {status}
- **Audit Time:** {now.isoformat()}

## Metric Verification
"""
        for name, data in results.items():
            if "error" in data:
                report += f"- **{name}:** ERROR — {data['error']}\n"
            else:
                icon = "OK" if data["ok"] else "BREACH"
                report += f"- **{name}:** {data['value']:.1f} (threshold: {data['threshold']}) [{icon}]\n"

        if not resolved:
            report += """
## Recommended Level 2 Actions
1. Rollback to last stable container image
2. If persistent, trigger graceful node shutdown
3. Escalate to on-call engineer
4. Review agent reasoning logs for potential misconfiguration
"""
        else:
            report += "\n## Resolution\nThe automated fix resolved the issue. No further action needed.\n"

        report += f"\n---\n*Generated by ASH-Fabric Audit Agent at {now.isoformat()}*\n"

        # Save to disk
        self._save_report(service, now, report)

        return report

    def _save_report(self, service: str, timestamp: datetime, report: str):
        """Save post-mortem report to the logs directory."""
        log_dir = Path(self.settings.log_dir) / "postmortems"
        log_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{timestamp.strftime('%Y%m%d_%H%M%S')}_{service}.md"
        report_path = log_dir / filename
        report_path.write_text(report)
        logger.info("postmortem_saved", path=str(report_path))
